service: serverless-workshop

plugins:
  - serverless-plugin-chrome
  - serverless-offline

custom:
  chrome:
    flags:
      - --window-size=1280,1696
      - --hide-scrollbars
      - --headless
      - --no-sandbox # If you can't run Chrome, uncomment this line.
    functions:
      - diff

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    DEBUG: "*"

functions:
  store:
    handler: screenshot/store.handler
    events:
      - http:
          path: /store/{id}
          method: put
          cors: true
  diff:
    handler: screenshot/diff.handler
    events:
      - http:
          path: /diff/{id}
          method: post
          cors: true
